openapi: 3.0.3
info:
  title: Bazaar APIs
  contact:
    email: info@paziresh24.com
  version: 1.0.0
servers:
  - url: https://bazaar.paziresh24.com/api/v1
tags:
  - name: Apps
    description: Everything about Apps
paths:
  /apps:
    get:
      tags:
        - Apps
      summary: Get All Apps
      operationId: getApps
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                     - $ref: '#/components/schemas/App'
  /apps/{id}:
    get:
      tags:
        - Apps
      summary: Find app by ID
      description: Returns a single app
      operationId: getAppById
      parameters:
        - name: id
          in: path
          description: ID of app to return
          required: true
          example: 10
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
components:
  schemas:
    App:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: نسخه نویسی پذیرش24
        description:
          type: string
          example: <p>...</p>
        short_description:
          type: string
          example: <p>...</p>
        price:
          type: string
          example: '100000'
        rating_count:
          type: number
          example: 10
        average_rating:
          type: string
          example: '4.5'
        logo:
          $ref: '#/components/schemas/Photo'
        gallery:
          type: array
          items:
            $ref: '#/components/schemas/Photo'
        tags:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string    
          example: "نسخه نویسی"
    Photo:
      type: object
      properties:
        src:
          type: string
          example: "https://bazaar.paziresh24.com/.../photo.png"
        alt:
          type: string
          example: ""
