openapi: 3.0.0
info:
  description: "API documentation for sending push notifications to Paziresh24 users."
  version: "1.0.0"
  title: "Paziresh24 Push Notification API"
servers:
  - url: "https://apigw.paziresh24.com"
paths:
  /v1/notification/push:
    post:
      summary: "Send a Push Notification"
      description: "This endpoint sends a push notification to a specific Paziresh24 user."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                user_id:
                  type: "string"
                  description: "Unique identifier of the user to receive the notification."
                title:
                  type: "string"
                  description: "Title of the push notification."
                text:
                  type: "string"
                  description: "Text content of the push notification."
                link:
                  type: "string"
                  description: "URL to be included in the notification, if any."
                image:
                  type: "string"
                  description: "URL of an image to be included in the notification."
                date:
                  type: "string"
                  description: "Unix timestamp when the notification is scheduled to be sent, formatted as a string."
              required:
                - user_id
                - title
                - text
      responses:
        '202':
          description: "Request accepted."
        '401':
          description: "Unauthorized - Invalid authorization."
      security:
        - authorizations: []
components:
  securitySchemes:
    authorizations:
      type: apiKey
      in: header
      name: token
      description: "The `authorizations` header is a unique token that grants access to the Paziresh24 Notification API. To obtain your authorization, please contact our support at support@paziresh24.com."
security:
  - authorizations: []
